### PR TITLE
Added splits json

### PR DESCRIPTION
**Pull request by emanuelevivoli**
# Data folder

I added the split jsons generated by @furkanbiten scripts.
I also added README.md to explain how the splits have been generated.

### CODE REVIEW

**Comment by emanuelevivoli** [comment]
`/data` folder moved to `/src/data`

**Comment by andreagemelli** [comment]
LGTM
can you create a model folder to `/src/models`?

**Comment by andreagemelli** [comment]
you are amazing man!
I think we can close this.

**Comment by andreagemelli** [comment]
Fuck, I need to merge it first lol

**Comment by andreagemelli** [comment]
GGWP 🔥

**Pull request merged**
